该数据集中的每个样本包含患者的年龄、近视/远视、是否散光、流泪量4个特征，以及医生推荐他们佩戴的隐形眼镜类型（硬材质、软材质、不佩戴）。使用该数据集可以构造一棵决策树，帮助医生给患者推荐应佩戴眼镜的类型。

![隐形眼镜数据集](../dataset/lenses/pic01.png)

In [1]:
import numpy as np
import decision_tree as DT
from decisiontreeplotter import DecisionTreePlotter

import importlib
import os

importlib.reload(DT)

<module 'decision_tree' from '/root/sdm274/assgn07_dt/decision_tree.py'>

In [2]:
# os.getcwd()
data = np.loadtxt('./lenses/lenses.data', dtype=int)
data

array([[ 1,  1,  1,  1,  1,  3],
       [ 2,  1,  1,  1,  2,  2],
       [ 3,  1,  1,  2,  1,  3],
       [ 4,  1,  1,  2,  2,  1],
       [ 5,  1,  2,  1,  1,  3],
       [ 6,  1,  2,  1,  2,  2],
       [ 7,  1,  2,  2,  1,  3],
       [ 8,  1,  2,  2,  2,  1],
       [ 9,  2,  1,  1,  1,  3],
       [10,  2,  1,  1,  2,  2],
       [11,  2,  1,  2,  1,  3],
       [12,  2,  1,  2,  2,  1],
       [13,  2,  2,  1,  1,  3],
       [14,  2,  2,  1,  2,  2],
       [15,  2,  2,  2,  1,  3],
       [16,  2,  2,  2,  2,  3],
       [17,  3,  1,  1,  1,  3],
       [18,  3,  1,  1,  2,  3],
       [19,  3,  1,  2,  1,  3],
       [20,  3,  1,  2,  2,  1],
       [21,  3,  2,  1,  1,  3],
       [22,  3,  2,  1,  2,  2],
       [23,  3,  2,  2,  1,  3],
       [24,  3,  2,  2,  2,  3]])

In [3]:
X = data[:, 1:-1]
y = data[:, -1]

dt01 = DT.DecisionTree()
dt01.train(X,y)

print(dt01)

Internal node <3>:
	[1]-> Leaf node (3)
	[2]-> Internal node <2>:
		[1]-> Internal node <0>:
			[1]-> Leaf node (2)
			[2]-> Leaf node (2)
			[3]-> Internal node <1>:
				[1]-> Leaf node (3)
				[2]-> Leaf node (2)
			
		
		[2]-> Internal node <1>:
			[1]-> Leaf node (1)
			[2]-> Internal node <0>:
				[1]-> Leaf node (1)
				[2]-> Leaf node (3)
				[3]-> Leaf node (3)
			
		
	



In [4]:
features_dict = {
    0: {'name': 'age', 'value_names': {1:'young', 
                                       2:'pre-presbyopic',
                                       3:'presbyopic'}
        },
    1: {'name':'prescript', 
        'value_names': {1: 'myope',
                        2: 'hypermetrope'}
        },
    2: {'name': 'astigmatic', 
        'value_names': {1: 'no', 
                        2: 'yes'}
    },
    3: {'name': 'tear rate', 
        'value_names': {1:'reduced', 
                        2:'normal'}
        },
}

label_dict = {
    1: 'hard',
    2: 'soft',
    3: 'no_lenses',
}

dtp = DecisionTreePlotter(dt01.tree_, feature_names = features_dict, label_names=label_dict)
dtp.plot()

In [7]:
# Predict the labels for the first 5 data points
predictions = dt01.predict(X[:5])
print(predictions)
print (y[:5])

# Calculate the accuracy of the model
accuracy = np.mean(predictions == y[:5])
print(accuracy)



[3 2 3 1 3]
[3 2 3 1 3]
1.0
